### PR TITLE
Fix Niten import problem

### PR DESCRIPTION
**Pull request by evemontalvao**
**CHANGELOG** :memo:

* We were having the following problem: in Gaiden, Niten import was done like `@import 'node_modules/@getninjas/niten-tokens/build/web/niten-tokens';` in `gaiden.scss` file and the files where the variables are used. This is bad because we needed an `import` in each file and also because in tanya, when we imported the `_colors.scss` css for example, the path `../../../node_modules/@getninjas/niten...` doesn't exist anymore, since Gaiden is also a module it doesn't have `node_modules`. So I created a script that can be run on the terminal to import Niten css into any project. Niten must be installed globally and to import into Gaiden, for example, the command would be `niten --path" src/scss/shared"`

### CODE REVIEW

**Comment by eduardojmatos** [comment]
@evemontalvao the script generates files to Gaiden, is this it?

**Comment by williamcosta** [comment]
@evemontalvao configure peer-dependency did not work?

**Comment by evemontalvao** [comment]
> @evemontalvao configure peer-dependency did not work?

@williamcosta It solved one problem, the "not found error" on Gaiden node_modules, but the variables still needed to be imported on every file where it'd be used 😞  seems like sass don't recognise a file from `node_modules` as a file with global variables, only local.

**Comment by evemontalvao** [comment]
> @evemontalvao the script generates files to Gaiden, is this it?

@eduardojmatos yep!

**Pull request merged**
